name: Fabric CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Project"
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: "Run Fabric Tests"
      uses: Geometrically/fabric-test-runner@v1
      with:
        minecraftVersion: 1.16.4
    
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: Builds
        path: build/libs
